version: '3.1'

services:

  mongo:
    image: mongo:4-bionic
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: showcase
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  showcase:
    build:
      context: .
    ports:
      - 8080:8080
      - 8000:8000
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000
    depends_on:
      - mongo

