version: '3.1'

services:

  showcase:
    build:
      context: .
    ports:
      - 8080:8080
      - 8000:8000
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000