server:
  port: 8080
  servlet:
    application-display-name: showcase
spring:
  datasource:
    username: showcase
    password: password
    url: jdbc:h2:mem:showcase
    driverClassName: org.h2.Driver
    database-platform: org:hibernate:dialect:H2Dialect
  h2:
    console:
      enabled: true
management:
  endpoint:
    health:
      show-details: always
      show-components: always
      enabled: true
    info:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health, info, env