server:
  port: 8080
  servlet:
    application-display-name: showcase
  ibm:
    mq:
      queueManager: QM1
      channel: DEV.ADMIN.SVRCONN
      connName: localhost(1414)
      user: admin
      password: passw0rd