server:
  port: 8080
  servlet:
    application-display-name: showcase
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: db
      password: dbpass
      database: showcase
