spring:
  quartz:
    job-store-type: jdbc
    properties.org.quartz.threadPool.threadCount: 5
    properties:
      org:
        quartz:
          jobStore:
            driverDelegateClass: "org.quartz.impl.jdbcjobstore.PostgreSQLDelegate"
    wait-for-jobs-to-complete-on-shutdown: true
    jdbc:
      initialize-schema: never

  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres?currentSchema=showcase"
    username: "postgres"
    password: "Passw0rd"