spring:
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          jobStore:
            driverDelegateClass: "org.quartz.impl.jdbcjobstore.PostgreSQLDelegate"
    wait-for-jobs-to-complete-on-shutdown: true
    jdbc:
      initialize-schema: never

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password