CREATE TABLE BOOK
(
    ID          VARCHAR,
    EXTERNAL_ID VARCHAR,
    NAME        VARCHAR,
    PRIMARY KEY (ID)
);

CREATE TABLE AUTHOR
(
    ID   VARCHAR,
    NAME VARCHAR,
    PRIMARY KEY (ID)
);

CREATE TABLE BOOK_AUTHOR
(
    ID        VARCHAR,
    BOOK_ID   VARCHAR NOT NULL,
    AUTHOR_ID VARCHAR NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK (ID),
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR (ID)
);